CUDA_VISIBLE_DEVICES=0,1 python gallop/train.py \
    --clip_name clip_vit_b16 \
    --exp_name eurosat_shot_16 \
    --save_dir ./results \
    --dataset_name eurosat \
    --max_epoch 200 \
    --batch_size 10 \
    --eval_ood True \
    --eval_domains True \
    --eval_freq 100 \
    --checkpointing_segments 0 \
    --use_local_features True \
    --lr_init 0.002 \
    --warmup_epoch 0 \
    --num_shots 16 \
    --parallel_text_encoder True \
    --parallel_vision_encoder True \
    --use_global_loss True \
    --learn_global_prompt True \
    --n_global_prompts 4 \
    --use_local_loss True \
    --learn_local_proj True \
    --learn_local_prompt True \
    --n_local_prompts 4 \
    --topk 5 10 15 20